"$schema" = 'https://starship.rs/config-schema.json'

format = """
┌$username\
$hostname\
$git_branch\
$git_status\
$directory\
$time\
\n$character"""

[git_branch]
symbol = "|┘"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ⚪ $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
disabled = false
success_symbol = '[└⮚](bold fg:color_green)'
error_symbol = '[└⮚](bold fg:color_red)'
vimcmd_symbol = '[⮘┘](bold fg:color_green)'
vimcmd_replace_one_symbol = '[⮘┘](bold fg:color_purple)'
vimcmd_replace_symbol = '[⮘┘](bold fg:color_purple)'
vimcmd_visual_symbol = '[⮘┘](bold fg:color_yellow)'